// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugICViU_xuGfDT8hKNrp9dPAVBumjYxo',
    appId: '1:421835633469:web:69f30ced7fe6fb2709cb54',
    messagingSenderId: '421835633469',
    projectId: 'todo-48d77',
    authDomain: 'todo-48d77.firebaseapp.com',
    storageBucket: 'todo-48d77.appspot.com',
    measurementId: 'G-VNBKHSBZDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJUGk7PmTqn07beRZHtE_Zr5uwMlwBAI',
    appId: '1:421835633469:android:ddae358bf952415b09cb54',
    messagingSenderId: '421835633469',
    projectId: 'todo-48d77',
    storageBucket: 'todo-48d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0QWFZ1juckHytBBU7CqkQEMMO24FxrE0',
    appId: '1:421835633469:ios:f698db91ab3dee7509cb54',
    messagingSenderId: '421835633469',
    projectId: 'todo-48d77',
    storageBucket: 'todo-48d77.appspot.com',
    iosClientId: '421835633469-gl709jf3u9ka35olu8adqupsmgt7pinj.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0QWFZ1juckHytBBU7CqkQEMMO24FxrE0',
    appId: '1:421835633469:ios:1a8b38a752ccfb9009cb54',
    messagingSenderId: '421835633469',
    projectId: 'todo-48d77',
    storageBucket: 'todo-48d77.appspot.com',
    iosClientId: '421835633469-nvpsfkanuu9f3k4l274grclatfducpgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
